### ISSUE TITLE
Color constructor is too smart

### ISSUE THREAD

**Issue by Meorawr** [Ellypse/Ellyb#11]
One issue with the design of the Color class is the constructor attempts to be too clever with the given values, accepting 0-1, 1-255, and hex inputs.

This isn't too bad, it's great for 99.9% of scenarios, but it does lead to subtle bugs where for example if the user has a custom color picker addon and they select an RGB value of (1, 1, 1) it'll get parsed as being fully white rather than mostly-black.

One such case where you'd run into this is actually the custom psycho trait colors in TRP3 - I've got ColorPickerPlus installed so if I use the default picker I can use the R/G/B input fields it provides. Setting them all to 1 would make the bar white, not black.

I think it'd be better to have some static constructors on the class (`Color:fromRGBA`, `Color:fromRGBAAsBytes`) to explicitly control what type of data range you're passing in when constructing the object. Thoughts?

**Comment by Ellypse** [comment]
I completely agree with you. The fact that it is not possible **at all** to create a color with RGB values of (1, 1, 1) on a 0-255 scale is a huge oversight.

I will add explicit constructors to use when you are sure of the format of the numbers.

**Comment by Meorawr** [comment]
Pretty sure Github still doesn't let people PR against wiki pages, but here's a slightly messy diff with the newly added constructors for the docs if you get a chance.

``````diff
diff --git a/Color.md b/Color.md
index 43929b2..7cdab0d 100644
--- a/Color.md
+++ b/Color.md
@@ -1,6 +1,8 @@
 The Color model provides methods to handle colors and colored text.
 
-## Color(red, green, blue, [alpha]) or Color(colorCode) or Color(colorTable)
+# Constructor
+
+## Color(red, green, blue[, alpha]) or Color(colorCode) or Color(colorTable)
 
 Constructor. Used to create a new Color.
 
@@ -10,7 +12,41 @@ local yellow = Ellyb.Color(255, 255, 0);
 local grey = Ellyb.Color("#CCC");
 local purple = Ellyb.Color({ r = 1, g = 0, b = 1});
 ```
- 
+
+**Note:** The `Color(red, green, blue[, alpha])` signature accepts values in either a floating point range and a byte value range. The byte value range is deprecated; see `Color:CreateFromRGBAsBytes()`.
+
+# Static Methods
+
+## CreateFromRGBA(red, green, blue[, alpha])
+
+Constructs a new `Color` instance with the given RGBA values treated as floating point values in the range 0-1.
+
+```lua
+local mahogany = Ellyb.Color:CreateFromRGBA(0.75, 0.25, 0);
+```
+
+## CreateFromRGBAAsBytes(red, green, blue[, alpha])
+
+Constructs a new `Color` instance with the given RGBA values treated as byte values in the range 0-255.
+
+Unlike the class constructor, this static method is capable of constructing a `Color` correctly when the input values are all equal to 1.
+
+```lua
+local malachite = Ellyb.Color:CreateFromRGBAAsBytes(11, 218, 81);
+```
+
+## CreateFromHexa(colorCode)
+
+Constructs a new `Color` instance with the given RGBA hexadecimal color code in the form `#RGB`, `#RRGGBB`, or `#RRGGBBAA`.
+
+Any prefixing `#` or present `|c` UI escape sequence will be stripped automatically (see `ColorManager.hexaToNumber`).
+
+```lua
+local azure = Ellyb.Color:CreateFromHexa("#0080ff");
+```
+
+# Instance Methods
+
 ## __tostring()
 
 Get a text representation of the Color: the hexadecimal code of the Color, colored using [UI escape sequences].
``````

**Comment by Ellypse** [comment]
Thanks :D It is updated, I just fixed the usage of  `:` instead of `.`. Since they are static methods they do not use the `:` notation that passes `self` :)

**Comment by Meorawr** [comment]
I should have proofread it some more, but the deprecation notice should point to `Color.CreateFromRGBAAsBytes` (had the colon and was missing the A in RGBA).

**Comment by Ellypse** [comment]
Fixed :)
