### ISSUE TITLE
[8.0] Deferred XML Node object named ... already exists

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Ellyb#20]
Known issue but just so it isn't forgotten, using Total RP 3 & Storyline together brings multiple errors from Ellyb on load : `Deferred XML Node object named ... already exists`

List of XML objects : `Ellyb_LogsFrame, Ellyb_CursorFrameTemplate, Ellyb_ChatInputTextures, Ellyb_PopupButton, Ellyb_PopupButton_Okay, Ellyb_StaticPopTemplate`

**Comment by Ellypse** [comment]
What should be done:

- [ ] Convert all existing XML templates to Lua factories to create frames (if necessary) in Lua only on runtime.
- [ ] Some XML templates can be transformed into being just util functions to be called on existing frames.

**Comment by Ellypse** [comment]
Note: This issue has been silenced for now, but we still need to move away from XML and then remove the code that silences those issues.
